import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "./globals.css"
import { NavMenu } from "@/components/nav-menu/nav-menu";
import { SessionProvider } from "next-auth/react";
import { PropsWithChildren } from "react";
import { Session } from "next-auth";
// import { getServerAuthSession } from "@/backend/authentication/auth";
const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900"
  ]
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  session,
  children,
}: PropsWithChildren<{session: Session | null}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <SessionProvider session={session}>
          <NavMenu/>
        
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
